# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [4]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [6]:
A = np.arange(1, 16).reshape(3,5)

In [7]:
print(f'The array dimension is {A.ndim}.')
print(f'The shape of the array is {A.shape[0]} columns and {A.shape[1]} rows.')
print(f'The array size is {A.size}.')
print(f'The array datatype is integers, {A.dtype.name}.')

The array dimension is 2.
The shape of the array is 3 columns and 5 rows.
The array size is 15.
The array datatype is integers, int64.


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [9]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [10]:
print('Elementwise subtraction')
print(B - C)
print()
print('Elementwise multiplication')
print(B * C)
print()
print('Matrix multiplication')  #(1*2)+(2*2)+(3*2)=12 in first row, first column
print(B @ C)

Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [12]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(np.exp(B))
print()
print(f'Minimum value in array is {B.min()}')
print(f'Minimum value in each row is {B.min(axis = 1)}')
print(f'Minimum value in each column is {B.min(axis = 0)}')
print(f'Index for minimum value is {B.argmin()}.')
print(f'Index for minimum value in each row is {B.argmin(axis=1)}.')
print(f'The sum of all elements is {B.sum()}.')
print(f'The mean for each column is {B.mean(axis = 0)}.')
print(f'The median for each column is {np.median(B, axis=0)}')

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in array is 1
Minimum value in each row is [1 4 7]
Minimum value in each column is [1 2 3]
Index for minimum value is 0.
Index for minimum value in each row is [0 0 0].
The sum of all elements is 45.
The mean for each column is [4. 5. 6.].
The median for each column is [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [15]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [16]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

fewer indices then number of axes -> missing indicies = complete slices, A[1] = A[1, 0:2] = A[1, :]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [20]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [22]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [24]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Creates integers from 0 to 29 assigned to variable a.
b is a reshape from 1D array to a 3D array with the dimension 2x3x5 (doesn't change array a)
Specified "2" first dimension
Specified "3" second dimension
Specified "-1" automated calculation to fit all elements.


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [30]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)
print()
print(m1.shape)
print(m2.shape)

[[2 3]
 [4 5]]

(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [32]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [33]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [36]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, op):
    #Validation
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError ('Both matrices must be numpy array objects')
    if op not in ['add', 'multiply']:
        raise ValueError('Operation must be "add" or "multiply"')

    if op == 'add':
        #Validate that matrices dimensions
        if matrix1.shape != matrix2.shape:
            raise ValueError ('For addition the matrices must have the same dimensions')
        return matrix1 + matrix2

    else:  #op == 'multiply'
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError ('For multiplication, the number of columns in array 1 must equal number of rows in the second array')
        return matrix1 @ matrix2  #For element-wise multiplication use "return matrix1 * matrix2"
    

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

10.1.1

a) 1x2
b) 5x = 5(4, 3) = (20, 15)
c) 3x = 3(4, 3) = (12, 9)
d) 5x + 3x = (20, 15) + (12, 9) = (32, 24)
e) 8x = 8(4, 3) = (32, 24)
f) 4x -x = 4(4, 3) - (4, 3) = (16, 12) - (4, 3) = ((16-4) - (12 - 3)) = (12, 9)
g) xT = 2x1
h) No, different dimension. 1x2 and 2x1.
i) ||x|| = (4^2 + 3^2)^0.5 = 25^0.5 = 5

10.1.2

a) 4x1

b) 2vT = (2x3, 2x7, 2x0, 2x11) = (6, 14, 0, 22) -> 2v = (6 
                                                        14 
                                                         0 
                                                        22)
                                                        
c) 5v + 2v = 7v = (7x3 = (21
                   7x7    49
                   7x0     0
                   7x11)  77)
                   
d) 4v - 2v = 2v = (6
                   14
                   0
                   22)
                   
e) vT = (3, 7, 0, 11), Dimension 1x4

f) ||vT|| = (3^2 + 7^2 + 0^2 + 11^2)^0.5 = 13.38 aprox

10.1.3

a) ||v1|| = (4^2 + 3^2 + 1^2 + 5^2)^0.5 = (51)^0.5 = 7.14 aprox
b) ||v1 - v2|| = ((4-2)^2 + (3-3)^2 + (1-1)^2 + (5-1)^2)^0.5 = 20^0.5 = 4.47 aprox

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

10.2.1

a) 2A = 4  2 -2
        2 -2 -2

b) B - 2A = 4 -2 -1 - 4  2 -2 = 0 -4  3
            2 -4 -2   2 -2 -2   0 -2 -4

c) Ej def

d) 2D - 3C = 6 8 - 3 6 = 3 2
             8 6   6 3   2 3

e) DT + 2D = 3 4 + 6 8 = 9 12
             4 3   8 6   12 9

f) 2CT - 2DT = 2(1 2) - 2(3 4) = 2 4 - 6 8 = -4 -4
                 2 1      4 3    4 2   8 6   -4 -4

g) AT har dimension 3x2 och B har dimension 2x3 -> Ej def

h) AC -> A har dim 2x3 och C har dim 2x2, 3 != 2 -> Ej def

i) CD = (1 2)  (3 4) = 1x3+2x4 1x4+2x3 = 11 10
         2 1    4 3    2x3+1x4 2x4+1x3   10 11

j) CB = (1 2) (4 -2  1) = ((1x4 + 2x2)  (-2+(-8))  (1+(-4)) = 8 -10 -3  Dimension 2x3
         2 1   2 -4 -2     (2x4 + 1x2    -4+(-4)    2+(-2)   10  -8  0

k) CI = (1 2)  (1 0) = ((1x1 + 2x0)  (1x0 + 2x1) = 1 2
         2 1    0 1      2x1 + 1x0    2x0 + 1x1    2 1

l) A dim = 2x3, BT dim = 3x2 -> Def och dim kommer bli 2x2

   ABT = (2  1 -1) (4  2) = 2x4 +   1x(-2)  + (-1)x1   2x2 + 1x(-4)    + (-1)x(-2) = 5 2
          1 -1  1  -2 -4    1x4 + (-1)x(-2) +  1x1     1x2 + (-1)x(-4) + 1x(-2)      7 4
                    1 -2

# **10.2.1 med funktionen add_mult_matrices

In [44]:
import numpy as np
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([1, 2])
I = np.array([[1, 0], [0, 1]])

print('10.2.1.a:')
print(add_mult_matrices(A, A, 'add'))
print()
print('10.2.1.b:')
print(add_mult_matrices(B, -2*A, 'add'))
print()
print('10.2.1.c:')
print()
print('10.2.1.d:')
print(add_mult_matrices(2*D, -3*C, 'add'))
print()
print('10.2.1.e:')
print(add_mult_matrices(D.T, 2*D, 'add'))
print()
print('10.2.1.f:')
print(add_mult_matrices(2*C.T,-2*D.T,'add'))
print()
print('10.2.1.g:')
print()
print('10.2.1.h:')
print()
print('10.2.1.i:')
print(add_mult_matrices(C, D, 'multiply'))
print()
print('10.2.1.j:')
print(add_mult_matrices(C, B, 'multiply'))
print()
print('10.2.1.k:')
print(add_mult_matrices(C, I, 'multiply'))
print()
print('10.2.1.l:')
print(add_mult_matrices(A, B.T, 'multiply'))

10.2.1.a:
[[ 4  2 -2]
 [ 2 -2  2]]

10.2.1.b:
[[ 0 -4  3]
 [ 0 -2 -4]]

10.2.1.c:

10.2.1.d:
[[3 2]
 [2 3]]

10.2.1.e:
[[ 9 12]
 [12  9]]

10.2.1.f:
[[-4 -4]
 [-4 -4]]

10.2.1.g:

10.2.1.h:

10.2.1.i:
[[11 10]
 [10 11]]

10.2.1.j:
[[  8 -10  -3]
 [ 10  -8   0]]

10.2.1.k:
[[1 2]
 [2 1]]

10.2.1.l:
[[5 2]
 [7 4]]


# 10.2.2  manuell

AAT = 2 3 4  2 5 = 2x2 + 3x3 + 4x4   2x5 + 3x4 + 4x1 = 29 26
      5 4 1  3 4   5x2 + 4x3 + 1x4   5x5 + 4x4 + 1x1   26 42
             4 1

In [46]:
# 10.2.2 med funktionen
A = np.array([[2, 3, 4], [5, 4, 1]])
print(add_mult_matrices(A, A.T, 'multiply'))

[[29 26]
 [26 42]]


# 10.2.3 manuell

AB = 1x2 + 2x1  1x1 + 2x3 = 4 7
     2x2 + 4x1  2x1 + 4x3   8 14

AC = 1x4 + 2x0  1x3 + 2x2 = 4 7
     2x4 + 4x0  2x3 + 4x2   8 14

BC = 2x4 + 1x0  2x3 + 1x2 = 8 8
     1x4 + 3x0  1x3 + 3x2   4 9
-> V.S.B.

In [48]:
# 10.2.3 med funktionen
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print('AB:')
print(add_mult_matrices(A, B, 'multiply'))
print()
print('AC:')
print(add_mult_matrices(A, C, 'multiply'))
print()
print('BC:')
print(add_mult_matrices(B, C, 'multiply'))
print()
print(' AB = AC != BC, V.S.B')

AB:
[[ 4  7]
 [ 8 14]]

AC:
[[ 4  7]
 [ 8 14]]

BC:
[[8 8]
 [4 9]]

 AB = AC != BC, V.S.B


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [51]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [52]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [53]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Check if v2.base returns the array 1, then it is a view and changes in v2 will also be made in v1.